# This is the configuration file for golangci-lint (https://golangci-lint.run)
# A demo file containing all possible options can be found at https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet # reports suspicious constructs
    - ineffassign # detect ineffectual assignments
    - staticcheck
    - typecheck
    - unused
    - gosec # inspects source code for security problems
    - dogsled # checks assignments with too many blank identifiers; default is 2
    - bodyclose # checks whether HTTP response body is closed successfully
    - unconvert # remove unnecessary type conversions
    - unparam # reports unused function parameters
