global:
  resolve_timeout: "5m"
  smtp_from: "form smtp"
  smtp_smarthost: "very smart"
  smtp_auth_username: "name"
  smtp_auth_password: "password"
  smtp_auth_identity: "smart identity"
  opsgenie_api_key: "api key"
  opsgenie_api_url: "api url"
route:
  receiver: "receiver"
  group_by:
    - "group"
    - "by"
  group_wait: "group wait"
  group_interval: "group_interval"
  repeat_interval: "repeat_interval"
  match:
    "key1": "value1"
    "key2": "value2"
  match_re:
    "key1": "value1"
    "key2": "value2"
  matchers:
    - "matcher1"
    - "matcher2"
  routes:
    - receiver: "receiver"
      group_by:
        - "group"
        - "by"
      group_wait: "group wait"
      group_interval: "group_interval"
      repeat_interval: "repeat_interval"
      match:
        "key1": "value1"
        "key2": "value2"
      match_re:
        "key1": "value1"
        "key2": "value2"
      matchers:
        - "matcher1"
        - "matcher2"
      routes:
        - receiver: "receiver"
          group_by:
            - "group"
            - "by"
          group_wait: "group wait"
          group_interval: "group_interval"
          repeat_interval: "repeat_interval"
          match:
            "key1": "value1"
            "key2": "value2"
          match_re:
            "key1": "value1"
            "key2": "value2"
          matchers:
            - "matcher1"
            - "matcher2"
    - receiver: "receiver"
      group_by:
        - "group"
        - "by"
      group_wait: "group wait"
      group_interval: "group_interval"
      repeat_interval: "repeat_interval"
      match:
        "key1": "value1"
        "key2": "value2"
      match_re:
        "key1": "value1"
        "key2": "value2"
      matchers:
        - "matcher1"
        - "matcher2"
      routes:
        - receiver: "receiver"
          group_by:
            - "group"
            - "by"
          group_wait: "group wait"
          group_interval: "group_interval"
          repeat_interval: "repeat_interval"
          match:
            "key1": "value1"
            "key2": "value2"
          match_re:
            "key1": "value1"
            "key2": "value2"
          matchers:
            - "matcher1"
            - "matcher2"
receivers:
  - name: "receiver1"
    email_configs:
      - to: "to"
        from: "from"
        smarthost: "smarthost"
        auth_username: "username"
        auth_password: "pass"
        auth_identity: "identity"
      - to: "to"
        from: "from"
        smarthost: "smarthost"
        auth_username: "username"
        auth_password: "pass"
        auth_identity: "identity"
    opsgenie_configs:
      - api_key: "key"
        api_url: "url"
        tags: "tag"
      - api_key: "key"
        api_url: "url"
        tags: "tag"
    webhook_configs:
      - url: "url"
        ms_teams: true
      - url: "url"
        ms_teams: false
  - name: "receiver2"
    email_configs:
      - to: "to"
        from: "from"
        smarthost: "smarthost"
        auth_username: "username"
        auth_password: "pass"
        auth_identity: "identity"
      - to: "to"
        from: "from"
        smarthost: "smarthost"
        auth_username: "username"
        auth_password: "pass"
        auth_identity: "identity"
    opsgenie_configs:
      - api_key: "key"
        api_url: "url"
        tags: "tag"
      - api_key: "key"
        api_url: "url"
        tags: "tag"
    webhook_configs:
      - url: "url"
        ms_teams: true
      - url: "url"
        ms_teams: false
inhibit_rules:
  - source_match:
      "key1": "value1"
      "key2": "value2"
    source_match_re:
      "key1": "value1"
      "key2": "value2"
    target_match:
      "key1": "value1"
      "key2": "value2"
    target_match_re:
      "key1": "value1"
      "key2": "value2"
    equal:
      - "1"
      - "2"
  - source_match:
      "key1": "value1"
      "key2": "value2"
    source_match_re:
      "key1": "value1"
      "key2": "value2"
    target_match:
      "key1": "value1"
      "key2": "value2"
    target_match_re:
      "key1": "value1"
      "key2": "value2"
    equal:
      - "1"
      - "2"
