- static_configs:
    - targets:
        - "target1"
        - "target2"
      labels:
        "key1":
          - "value1"
          - "value2"
        "key2":
          - "value1"
          - "value2"
    - targets:
        - "target1"
        - "target2"
      labels:
        "key1":
          - "value1"
          - "value2"
        "key2":
          - "value1"
          - "value2"
  job_name: "job"
  scheme: "https"
  scrape_interval: "5m"
  scrape_timeout: "10s"
  metrics_path: "/metrics"
  sample_limit: 42
  basic_auth:
    username: "username"
    password: "password"
  oauth2:
    client_id: "id"
    client_secret: "secret"
    token_url: "url"
    scopes:
      - "1"
      - "2"
    tls_config:
      insecure_skip_verify: true
  tls_config:
    insecure_skip_verify: true
  bearer_token: "token"
  metric_relabel_configs:
    - source_labels:
        - "label1"
        - "label2"
      separator: ";"
      target_label: "label"
      regex: ".*"
      modulus: 42
      replacement: "$1"
      action: "keep"
    - source_labels:
        - "label1"
        - "label2"
      separator: ";"
      target_label: "label"
      regex: ".*"
      modulus: 42
      replacement: "$1"
      action: "keep"
  params:
    "key1":
      - "value1"
      - "value2"
    "key2":
      - "value1"
      - "value2"
  http_sd_configs:
    - url: "url"
      refresh_interval: "5m"
      basic_auth:
        username: "username"
        password: "password"
      oauth2:
        client_id: "id"
        client_secret: "secret"
        token_url: "url"
        scopes:
          - "1"
          - "2"
        tls_config:
          insecure_skip_verify: true
      tls_config:
        insecure_skip_verify: true
    - url: "url"
      refresh_interval: "5m"
      basic_auth:
        username: "username"
        password: "password"
      oauth2:
        client_id: "id"
        client_secret: "secret"
        token_url: "url"
        scopes:
          - "1"
          - "2"
        tls_config:
          insecure_skip_verify: true
      tls_config:
        insecure_skip_verify: true
  honor_labels: true
  honor_timestamps: true
