/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: v1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// PutAlert struct for PutAlert
type PutAlert struct {
	Message string `json:"message"`
	Data Alert `json:"data"`
}

// NewPutAlert instantiates a new PutAlert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutAlert(message string, data Alert) *PutAlert {
	this := PutAlert{}
	this.Message = message
	this.Data = data
	return &this
}

// NewPutAlertWithDefaults instantiates a new PutAlert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutAlertWithDefaults() *PutAlert {
	this := PutAlert{}
	return &this
}

// GetMessage returns the Message field value
func (o *PutAlert) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *PutAlert) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *PutAlert) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *PutAlert) GetData() Alert {
	if o == nil {
		var ret Alert
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PutAlert) GetDataOk() (*Alert, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PutAlert) SetData(v Alert) {
	o.Data = v
}

func (o PutAlert) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["message"] = o.Message
	}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullablePutAlert struct {
	value *PutAlert
	isSet bool
}

func (v NullablePutAlert) Get() *PutAlert {
	return v.value
}

func (v *NullablePutAlert) Set(val *PutAlert) {
	v.value = val
	v.isSet = true
}

func (v NullablePutAlert) IsSet() bool {
	return v.isSet
}

func (v *NullablePutAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutAlert(val *PutAlert) *NullablePutAlert {
	return &NullablePutAlert{value: val, isSet: true}
}

func (v NullablePutAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


