/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: 1.0
Contact: patrick.koss@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// V1InstancesScrapeconfigsCreateRequestParams Optional http params
type V1InstancesScrapeconfigsCreateRequestParams struct {
	String1 []string `json:"string1,omitempty"`
	String2 []string `json:"string2,omitempty"`
}

// NewV1InstancesScrapeconfigsCreateRequestParams instantiates a new V1InstancesScrapeconfigsCreateRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1InstancesScrapeconfigsCreateRequestParams() *V1InstancesScrapeconfigsCreateRequestParams {
	this := V1InstancesScrapeconfigsCreateRequestParams{}
	return &this
}

// NewV1InstancesScrapeconfigsCreateRequestParamsWithDefaults instantiates a new V1InstancesScrapeconfigsCreateRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1InstancesScrapeconfigsCreateRequestParamsWithDefaults() *V1InstancesScrapeconfigsCreateRequestParams {
	this := V1InstancesScrapeconfigsCreateRequestParams{}
	return &this
}

// GetString1 returns the String1 field value if set, zero value otherwise.
func (o *V1InstancesScrapeconfigsCreateRequestParams) GetString1() []string {
	if o == nil || o.String1 == nil {
		var ret []string
		return ret
	}
	return o.String1
}

// GetString1Ok returns a tuple with the String1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesScrapeconfigsCreateRequestParams) GetString1Ok() ([]string, bool) {
	if o == nil || o.String1 == nil {
		return nil, false
	}
	return o.String1, true
}

// HasString1 returns a boolean if a field has been set.
func (o *V1InstancesScrapeconfigsCreateRequestParams) HasString1() bool {
	if o != nil && o.String1 != nil {
		return true
	}

	return false
}

// SetString1 gets a reference to the given []string and assigns it to the String1 field.
func (o *V1InstancesScrapeconfigsCreateRequestParams) SetString1(v []string) {
	o.String1 = v
}

// GetString2 returns the String2 field value if set, zero value otherwise.
func (o *V1InstancesScrapeconfigsCreateRequestParams) GetString2() []string {
	if o == nil || o.String2 == nil {
		var ret []string
		return ret
	}
	return o.String2
}

// GetString2Ok returns a tuple with the String2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesScrapeconfigsCreateRequestParams) GetString2Ok() ([]string, bool) {
	if o == nil || o.String2 == nil {
		return nil, false
	}
	return o.String2, true
}

// HasString2 returns a boolean if a field has been set.
func (o *V1InstancesScrapeconfigsCreateRequestParams) HasString2() bool {
	if o != nil && o.String2 != nil {
		return true
	}

	return false
}

// SetString2 gets a reference to the given []string and assigns it to the String2 field.
func (o *V1InstancesScrapeconfigsCreateRequestParams) SetString2(v []string) {
	o.String2 = v
}

func (o V1InstancesScrapeconfigsCreateRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.String1 != nil {
		toSerialize["string1"] = o.String1
	}
	if o.String2 != nil {
		toSerialize["string2"] = o.String2
	}
	return json.Marshal(toSerialize)
}

type NullableV1InstancesScrapeconfigsCreateRequestParams struct {
	value *V1InstancesScrapeconfigsCreateRequestParams
	isSet bool
}

func (v NullableV1InstancesScrapeconfigsCreateRequestParams) Get() *V1InstancesScrapeconfigsCreateRequestParams {
	return v.value
}

func (v *NullableV1InstancesScrapeconfigsCreateRequestParams) Set(val *V1InstancesScrapeconfigsCreateRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableV1InstancesScrapeconfigsCreateRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableV1InstancesScrapeconfigsCreateRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1InstancesScrapeconfigsCreateRequestParams(val *V1InstancesScrapeconfigsCreateRequestParams) *NullableV1InstancesScrapeconfigsCreateRequestParams {
	return &NullableV1InstancesScrapeconfigsCreateRequestParams{value: val, isSet: true}
}

func (v NullableV1InstancesScrapeconfigsCreateRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1InstancesScrapeconfigsCreateRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
