/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: v1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// LogsConfig struct for LogsConfig
type LogsConfig struct {
	Retention string `json:"retention"`
}

// NewLogsConfig instantiates a new LogsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogsConfig(retention string) *LogsConfig {
	this := LogsConfig{}
	this.Retention = retention
	return &this
}

// NewLogsConfigWithDefaults instantiates a new LogsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogsConfigWithDefaults() *LogsConfig {
	this := LogsConfig{}
	return &this
}

// GetRetention returns the Retention field value
func (o *LogsConfig) GetRetention() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Retention
}

// GetRetentionOk returns a tuple with the Retention field value
// and a boolean to check if the value has been set.
func (o *LogsConfig) GetRetentionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Retention, true
}

// SetRetention sets field value
func (o *LogsConfig) SetRetention(v string) {
	o.Retention = v
}

func (o LogsConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["retention"] = o.Retention
	}
	return json.Marshal(toSerialize)
}

type NullableLogsConfig struct {
	value *LogsConfig
	isSet bool
}

func (v NullableLogsConfig) Get() *LogsConfig {
	return v.value
}

func (v *NullableLogsConfig) Set(val *LogsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableLogsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableLogsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogsConfig(val *LogsConfig) *NullableLogsConfig {
	return &NullableLogsConfig{value: val, isSet: true}
}

func (v NullableLogsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


