/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: 1.0
Contact: patrick.koss@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// PlanModel struct for PlanModel
type PlanModel struct {
	PlanId                  string   `json:"planId"`
	Description             *string  `json:"description,omitempty"`
	BucketSize              int32    `json:"bucketSize"`
	GrafanaGlobalUsers      int32    `json:"grafanaGlobalUsers"`
	GrafanaGlobalOrgs       int32    `json:"grafanaGlobalOrgs"`
	GrafanaGlobalDashboards int32    `json:"grafanaGlobalDashboards"`
	AlertRules              int32    `json:"alertRules"`
	TargetNumber            int32    `json:"targetNumber"`
	SamplesPerScrape        int32    `json:"samplesPerScrape"`
	GrafanaGlobalSessions   int32    `json:"grafanaGlobalSessions"`
	Name                    *string  `json:"name,omitempty"`
	Amount                  *float32 `json:"amount,omitempty"`
}

// NewPlanModel instantiates a new PlanModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanModel(planId string, bucketSize int32, grafanaGlobalUsers int32, grafanaGlobalOrgs int32, grafanaGlobalDashboards int32, alertRules int32, targetNumber int32, samplesPerScrape int32, grafanaGlobalSessions int32) *PlanModel {
	this := PlanModel{}
	this.PlanId = planId
	this.BucketSize = bucketSize
	this.GrafanaGlobalUsers = grafanaGlobalUsers
	this.GrafanaGlobalOrgs = grafanaGlobalOrgs
	this.GrafanaGlobalDashboards = grafanaGlobalDashboards
	this.AlertRules = alertRules
	this.TargetNumber = targetNumber
	this.SamplesPerScrape = samplesPerScrape
	this.GrafanaGlobalSessions = grafanaGlobalSessions
	return &this
}

// NewPlanModelWithDefaults instantiates a new PlanModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanModelWithDefaults() *PlanModel {
	this := PlanModel{}
	return &this
}

// GetPlanId returns the PlanId field value
func (o *PlanModel) GetPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetPlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *PlanModel) SetPlanId(v string) {
	o.PlanId = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PlanModel) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanModel) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PlanModel) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PlanModel) SetDescription(v string) {
	o.Description = &v
}

// GetBucketSize returns the BucketSize field value
func (o *PlanModel) GetBucketSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BucketSize
}

// GetBucketSizeOk returns a tuple with the BucketSize field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetBucketSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BucketSize, true
}

// SetBucketSize sets field value
func (o *PlanModel) SetBucketSize(v int32) {
	o.BucketSize = v
}

// GetGrafanaGlobalUsers returns the GrafanaGlobalUsers field value
func (o *PlanModel) GetGrafanaGlobalUsers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GrafanaGlobalUsers
}

// GetGrafanaGlobalUsersOk returns a tuple with the GrafanaGlobalUsers field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetGrafanaGlobalUsersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrafanaGlobalUsers, true
}

// SetGrafanaGlobalUsers sets field value
func (o *PlanModel) SetGrafanaGlobalUsers(v int32) {
	o.GrafanaGlobalUsers = v
}

// GetGrafanaGlobalOrgs returns the GrafanaGlobalOrgs field value
func (o *PlanModel) GetGrafanaGlobalOrgs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GrafanaGlobalOrgs
}

// GetGrafanaGlobalOrgsOk returns a tuple with the GrafanaGlobalOrgs field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetGrafanaGlobalOrgsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrafanaGlobalOrgs, true
}

// SetGrafanaGlobalOrgs sets field value
func (o *PlanModel) SetGrafanaGlobalOrgs(v int32) {
	o.GrafanaGlobalOrgs = v
}

// GetGrafanaGlobalDashboards returns the GrafanaGlobalDashboards field value
func (o *PlanModel) GetGrafanaGlobalDashboards() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GrafanaGlobalDashboards
}

// GetGrafanaGlobalDashboardsOk returns a tuple with the GrafanaGlobalDashboards field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetGrafanaGlobalDashboardsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrafanaGlobalDashboards, true
}

// SetGrafanaGlobalDashboards sets field value
func (o *PlanModel) SetGrafanaGlobalDashboards(v int32) {
	o.GrafanaGlobalDashboards = v
}

// GetAlertRules returns the AlertRules field value
func (o *PlanModel) GetAlertRules() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AlertRules
}

// GetAlertRulesOk returns a tuple with the AlertRules field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetAlertRulesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlertRules, true
}

// SetAlertRules sets field value
func (o *PlanModel) SetAlertRules(v int32) {
	o.AlertRules = v
}

// GetTargetNumber returns the TargetNumber field value
func (o *PlanModel) GetTargetNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TargetNumber
}

// GetTargetNumberOk returns a tuple with the TargetNumber field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetTargetNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetNumber, true
}

// SetTargetNumber sets field value
func (o *PlanModel) SetTargetNumber(v int32) {
	o.TargetNumber = v
}

// GetSamplesPerScrape returns the SamplesPerScrape field value
func (o *PlanModel) GetSamplesPerScrape() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SamplesPerScrape
}

// GetSamplesPerScrapeOk returns a tuple with the SamplesPerScrape field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetSamplesPerScrapeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SamplesPerScrape, true
}

// SetSamplesPerScrape sets field value
func (o *PlanModel) SetSamplesPerScrape(v int32) {
	o.SamplesPerScrape = v
}

// GetGrafanaGlobalSessions returns the GrafanaGlobalSessions field value
func (o *PlanModel) GetGrafanaGlobalSessions() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GrafanaGlobalSessions
}

// GetGrafanaGlobalSessionsOk returns a tuple with the GrafanaGlobalSessions field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetGrafanaGlobalSessionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrafanaGlobalSessions, true
}

// SetGrafanaGlobalSessions sets field value
func (o *PlanModel) SetGrafanaGlobalSessions(v int32) {
	o.GrafanaGlobalSessions = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PlanModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PlanModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PlanModel) SetName(v string) {
	o.Name = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *PlanModel) GetAmount() float32 {
	if o == nil || o.Amount == nil {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanModel) GetAmountOk() (*float32, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *PlanModel) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *PlanModel) SetAmount(v float32) {
	o.Amount = &v
}

func (o PlanModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["planId"] = o.PlanId
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["bucketSize"] = o.BucketSize
	}
	if true {
		toSerialize["grafanaGlobalUsers"] = o.GrafanaGlobalUsers
	}
	if true {
		toSerialize["grafanaGlobalOrgs"] = o.GrafanaGlobalOrgs
	}
	if true {
		toSerialize["grafanaGlobalDashboards"] = o.GrafanaGlobalDashboards
	}
	if true {
		toSerialize["alertRules"] = o.AlertRules
	}
	if true {
		toSerialize["targetNumber"] = o.TargetNumber
	}
	if true {
		toSerialize["samplesPerScrape"] = o.SamplesPerScrape
	}
	if true {
		toSerialize["grafanaGlobalSessions"] = o.GrafanaGlobalSessions
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullablePlanModel struct {
	value *PlanModel
	isSet bool
}

func (v NullablePlanModel) Get() *PlanModel {
	return v.value
}

func (v *NullablePlanModel) Set(val *PlanModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanModel(val *PlanModel) *NullablePlanModel {
	return &NullablePlanModel{value: val, isSet: true}
}

func (v NullablePlanModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
