/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: v1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// V1GrafanaPluginsUpdateRequest struct for V1GrafanaPluginsUpdateRequest
type V1GrafanaPluginsUpdateRequest struct {
	// Description of the grafana plugin to update
	Description string `json:"description"`
}

// NewV1GrafanaPluginsUpdateRequest instantiates a new V1GrafanaPluginsUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GrafanaPluginsUpdateRequest(description string) *V1GrafanaPluginsUpdateRequest {
	this := V1GrafanaPluginsUpdateRequest{}
	this.Description = description
	return &this
}

// NewV1GrafanaPluginsUpdateRequestWithDefaults instantiates a new V1GrafanaPluginsUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GrafanaPluginsUpdateRequestWithDefaults() *V1GrafanaPluginsUpdateRequest {
	this := V1GrafanaPluginsUpdateRequest{}
	return &this
}

// GetDescription returns the Description field value
func (o *V1GrafanaPluginsUpdateRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *V1GrafanaPluginsUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *V1GrafanaPluginsUpdateRequest) SetDescription(v string) {
	o.Description = v
}

func (o V1GrafanaPluginsUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableV1GrafanaPluginsUpdateRequest struct {
	value *V1GrafanaPluginsUpdateRequest
	isSet bool
}

func (v NullableV1GrafanaPluginsUpdateRequest) Get() *V1GrafanaPluginsUpdateRequest {
	return v.value
}

func (v *NullableV1GrafanaPluginsUpdateRequest) Set(val *V1GrafanaPluginsUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GrafanaPluginsUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GrafanaPluginsUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GrafanaPluginsUpdateRequest(val *V1GrafanaPluginsUpdateRequest) *NullableV1GrafanaPluginsUpdateRequest {
	return &NullableV1GrafanaPluginsUpdateRequest{value: val, isSet: true}
}

func (v NullableV1GrafanaPluginsUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GrafanaPluginsUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


