/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: 1.0
Contact: patrick.koss@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// V1InstancesGrafanaConfigsUpdateRequest struct for V1InstancesGrafanaConfigsUpdateRequest
type V1InstancesGrafanaConfigsUpdateRequest struct {
	// If it is true anyone can access the grafana dashboards without logging in. If it is false a login is required.
	PublicReadAccess bool `json:"publicReadAccess"`
}

// NewV1InstancesGrafanaConfigsUpdateRequest instantiates a new V1InstancesGrafanaConfigsUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1InstancesGrafanaConfigsUpdateRequest(publicReadAccess bool) *V1InstancesGrafanaConfigsUpdateRequest {
	this := V1InstancesGrafanaConfigsUpdateRequest{}
	this.PublicReadAccess = publicReadAccess
	return &this
}

// NewV1InstancesGrafanaConfigsUpdateRequestWithDefaults instantiates a new V1InstancesGrafanaConfigsUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1InstancesGrafanaConfigsUpdateRequestWithDefaults() *V1InstancesGrafanaConfigsUpdateRequest {
	this := V1InstancesGrafanaConfigsUpdateRequest{}
	return &this
}

// GetPublicReadAccess returns the PublicReadAccess field value
func (o *V1InstancesGrafanaConfigsUpdateRequest) GetPublicReadAccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PublicReadAccess
}

// GetPublicReadAccessOk returns a tuple with the PublicReadAccess field value
// and a boolean to check if the value has been set.
func (o *V1InstancesGrafanaConfigsUpdateRequest) GetPublicReadAccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicReadAccess, true
}

// SetPublicReadAccess sets field value
func (o *V1InstancesGrafanaConfigsUpdateRequest) SetPublicReadAccess(v bool) {
	o.PublicReadAccess = v
}

func (o V1InstancesGrafanaConfigsUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["publicReadAccess"] = o.PublicReadAccess
	}
	return json.Marshal(toSerialize)
}

type NullableV1InstancesGrafanaConfigsUpdateRequest struct {
	value *V1InstancesGrafanaConfigsUpdateRequest
	isSet bool
}

func (v NullableV1InstancesGrafanaConfigsUpdateRequest) Get() *V1InstancesGrafanaConfigsUpdateRequest {
	return v.value
}

func (v *NullableV1InstancesGrafanaConfigsUpdateRequest) Set(val *V1InstancesGrafanaConfigsUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1InstancesGrafanaConfigsUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1InstancesGrafanaConfigsUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1InstancesGrafanaConfigsUpdateRequest(val *V1InstancesGrafanaConfigsUpdateRequest) *NullableV1InstancesGrafanaConfigsUpdateRequest {
	return &NullableV1InstancesGrafanaConfigsUpdateRequest{value: val, isSet: true}
}

func (v NullableV1InstancesGrafanaConfigsUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1InstancesGrafanaConfigsUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
