/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: v1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// SystemInstanceResponse struct for SystemInstanceResponse
type SystemInstanceResponse struct {
	Message string `json:"message"`
	Instance SystemInstance `json:"instance"`
}

// NewSystemInstanceResponse instantiates a new SystemInstanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemInstanceResponse(message string, instance SystemInstance) *SystemInstanceResponse {
	this := SystemInstanceResponse{}
	this.Message = message
	this.Instance = instance
	return &this
}

// NewSystemInstanceResponseWithDefaults instantiates a new SystemInstanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemInstanceResponseWithDefaults() *SystemInstanceResponse {
	this := SystemInstanceResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *SystemInstanceResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SystemInstanceResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SystemInstanceResponse) SetMessage(v string) {
	o.Message = v
}

// GetInstance returns the Instance field value
func (o *SystemInstanceResponse) GetInstance() SystemInstance {
	if o == nil {
		var ret SystemInstance
		return ret
	}

	return o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value
// and a boolean to check if the value has been set.
func (o *SystemInstanceResponse) GetInstanceOk() (*SystemInstance, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instance, true
}

// SetInstance sets field value
func (o *SystemInstanceResponse) SetInstance(v SystemInstance) {
	o.Instance = v
}

func (o SystemInstanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["message"] = o.Message
	}
	if true {
		toSerialize["instance"] = o.Instance
	}
	return json.Marshal(toSerialize)
}

type NullableSystemInstanceResponse struct {
	value *SystemInstanceResponse
	isSet bool
}

func (v NullableSystemInstanceResponse) Get() *SystemInstanceResponse {
	return v.value
}

func (v *NullableSystemInstanceResponse) Set(val *SystemInstanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemInstanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemInstanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemInstanceResponse(val *SystemInstanceResponse) *NullableSystemInstanceResponse {
	return &NullableSystemInstanceResponse{value: val, isSet: true}
}

func (v NullableSystemInstanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemInstanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


