/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: 1.0
Contact: patrick.koss@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// PostAlertGroup struct for PostAlertGroup
type PostAlertGroup struct {
	Message string       `json:"message"`
	Data    []AlertGroup `json:"data"`
}

// NewPostAlertGroup instantiates a new PostAlertGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostAlertGroup(message string, data []AlertGroup) *PostAlertGroup {
	this := PostAlertGroup{}
	this.Message = message
	this.Data = data
	return &this
}

// NewPostAlertGroupWithDefaults instantiates a new PostAlertGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostAlertGroupWithDefaults() *PostAlertGroup {
	this := PostAlertGroup{}
	return &this
}

// GetMessage returns the Message field value
func (o *PostAlertGroup) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *PostAlertGroup) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *PostAlertGroup) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *PostAlertGroup) GetData() []AlertGroup {
	if o == nil {
		var ret []AlertGroup
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PostAlertGroup) GetDataOk() ([]AlertGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PostAlertGroup) SetData(v []AlertGroup) {
	o.Data = v
}

func (o PostAlertGroup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["message"] = o.Message
	}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullablePostAlertGroup struct {
	value *PostAlertGroup
	isSet bool
}

func (v NullablePostAlertGroup) Get() *PostAlertGroup {
	return v.value
}

func (v *NullablePostAlertGroup) Set(val *PostAlertGroup) {
	v.value = val
	v.isSet = true
}

func (v NullablePostAlertGroup) IsSet() bool {
	return v.isSet
}

func (v *NullablePostAlertGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostAlertGroup(val *PostAlertGroup) *NullablePostAlertGroup {
	return &NullablePostAlertGroup{value: val, isSet: true}
}

func (v NullablePostAlertGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostAlertGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
