/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: v1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// GetAllJob struct for GetAllJob
type GetAllJob struct {
	Message string `json:"message"`
	Data []Job `json:"data"`
}

// NewGetAllJob instantiates a new GetAllJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllJob(message string, data []Job) *GetAllJob {
	this := GetAllJob{}
	this.Message = message
	this.Data = data
	return &this
}

// NewGetAllJobWithDefaults instantiates a new GetAllJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllJobWithDefaults() *GetAllJob {
	this := GetAllJob{}
	return &this
}

// GetMessage returns the Message field value
func (o *GetAllJob) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GetAllJob) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GetAllJob) SetMessage(v string) {
	o.Message = v
}

// GetData returns the Data field value
func (o *GetAllJob) GetData() []Job {
	if o == nil {
		var ret []Job
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetAllJob) GetDataOk() ([]Job, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetAllJob) SetData(v []Job) {
	o.Data = v
}

func (o GetAllJob) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["message"] = o.Message
	}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetAllJob struct {
	value *GetAllJob
	isSet bool
}

func (v NullableGetAllJob) Get() *GetAllJob {
	return v.value
}

func (v *NullableGetAllJob) Set(val *GetAllJob) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllJob) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllJob(val *GetAllJob) *NullableGetAllJob {
	return &NullableGetAllJob{value: val, isSet: true}
}

func (v NullableGetAllJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAllJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


