/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: 1.0
Contact: patrick.koss@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// OpsgenieConfig struct for OpsgenieConfig
type OpsgenieConfig struct {
	ApiKey     *string     `json:"apiKey,omitempty"`
	ApiUrl     *string     `json:"apiUrl,omitempty"`
	Tags       *string     `json:"tags,omitempty"`
	HttpConfig *HttpConfig `json:"httpConfig,omitempty"`
}

// NewOpsgenieConfig instantiates a new OpsgenieConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsgenieConfig() *OpsgenieConfig {
	this := OpsgenieConfig{}
	return &this
}

// NewOpsgenieConfigWithDefaults instantiates a new OpsgenieConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsgenieConfigWithDefaults() *OpsgenieConfig {
	this := OpsgenieConfig{}
	return &this
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *OpsgenieConfig) GetApiKey() string {
	if o == nil || o.ApiKey == nil {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsgenieConfig) GetApiKeyOk() (*string, bool) {
	if o == nil || o.ApiKey == nil {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *OpsgenieConfig) HasApiKey() bool {
	if o != nil && o.ApiKey != nil {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *OpsgenieConfig) SetApiKey(v string) {
	o.ApiKey = &v
}

// GetApiUrl returns the ApiUrl field value if set, zero value otherwise.
func (o *OpsgenieConfig) GetApiUrl() string {
	if o == nil || o.ApiUrl == nil {
		var ret string
		return ret
	}
	return *o.ApiUrl
}

// GetApiUrlOk returns a tuple with the ApiUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsgenieConfig) GetApiUrlOk() (*string, bool) {
	if o == nil || o.ApiUrl == nil {
		return nil, false
	}
	return o.ApiUrl, true
}

// HasApiUrl returns a boolean if a field has been set.
func (o *OpsgenieConfig) HasApiUrl() bool {
	if o != nil && o.ApiUrl != nil {
		return true
	}

	return false
}

// SetApiUrl gets a reference to the given string and assigns it to the ApiUrl field.
func (o *OpsgenieConfig) SetApiUrl(v string) {
	o.ApiUrl = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *OpsgenieConfig) GetTags() string {
	if o == nil || o.Tags == nil {
		var ret string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsgenieConfig) GetTagsOk() (*string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *OpsgenieConfig) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given string and assigns it to the Tags field.
func (o *OpsgenieConfig) SetTags(v string) {
	o.Tags = &v
}

// GetHttpConfig returns the HttpConfig field value if set, zero value otherwise.
func (o *OpsgenieConfig) GetHttpConfig() HttpConfig {
	if o == nil || o.HttpConfig == nil {
		var ret HttpConfig
		return ret
	}
	return *o.HttpConfig
}

// GetHttpConfigOk returns a tuple with the HttpConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsgenieConfig) GetHttpConfigOk() (*HttpConfig, bool) {
	if o == nil || o.HttpConfig == nil {
		return nil, false
	}
	return o.HttpConfig, true
}

// HasHttpConfig returns a boolean if a field has been set.
func (o *OpsgenieConfig) HasHttpConfig() bool {
	if o != nil && o.HttpConfig != nil {
		return true
	}

	return false
}

// SetHttpConfig gets a reference to the given HttpConfig and assigns it to the HttpConfig field.
func (o *OpsgenieConfig) SetHttpConfig(v HttpConfig) {
	o.HttpConfig = &v
}

func (o OpsgenieConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiKey != nil {
		toSerialize["apiKey"] = o.ApiKey
	}
	if o.ApiUrl != nil {
		toSerialize["apiUrl"] = o.ApiUrl
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.HttpConfig != nil {
		toSerialize["httpConfig"] = o.HttpConfig
	}
	return json.Marshal(toSerialize)
}

type NullableOpsgenieConfig struct {
	value *OpsgenieConfig
	isSet bool
}

func (v NullableOpsgenieConfig) Get() *OpsgenieConfig {
	return v.value
}

func (v *NullableOpsgenieConfig) Set(val *OpsgenieConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsgenieConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsgenieConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsgenieConfig(val *OpsgenieConfig) *NullableOpsgenieConfig {
	return &NullableOpsgenieConfig{value: val, isSet: true}
}

func (v NullableOpsgenieConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsgenieConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
