/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: 1.0
Contact: patrick.koss@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// GrafanaConfigsSerializerRespond struct for GrafanaConfigsSerializerRespond
type GrafanaConfigsSerializerRespond struct {
	PublicReadAccess bool   `json:"publicReadAccess"`
	Message          string `json:"message"`
}

// NewGrafanaConfigsSerializerRespond instantiates a new GrafanaConfigsSerializerRespond object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrafanaConfigsSerializerRespond(publicReadAccess bool, message string) *GrafanaConfigsSerializerRespond {
	this := GrafanaConfigsSerializerRespond{}
	this.PublicReadAccess = publicReadAccess
	this.Message = message
	return &this
}

// NewGrafanaConfigsSerializerRespondWithDefaults instantiates a new GrafanaConfigsSerializerRespond object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrafanaConfigsSerializerRespondWithDefaults() *GrafanaConfigsSerializerRespond {
	this := GrafanaConfigsSerializerRespond{}
	return &this
}

// GetPublicReadAccess returns the PublicReadAccess field value
func (o *GrafanaConfigsSerializerRespond) GetPublicReadAccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PublicReadAccess
}

// GetPublicReadAccessOk returns a tuple with the PublicReadAccess field value
// and a boolean to check if the value has been set.
func (o *GrafanaConfigsSerializerRespond) GetPublicReadAccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicReadAccess, true
}

// SetPublicReadAccess sets field value
func (o *GrafanaConfigsSerializerRespond) SetPublicReadAccess(v bool) {
	o.PublicReadAccess = v
}

// GetMessage returns the Message field value
func (o *GrafanaConfigsSerializerRespond) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *GrafanaConfigsSerializerRespond) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *GrafanaConfigsSerializerRespond) SetMessage(v string) {
	o.Message = v
}

func (o GrafanaConfigsSerializerRespond) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["publicReadAccess"] = o.PublicReadAccess
	}
	if true {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableGrafanaConfigsSerializerRespond struct {
	value *GrafanaConfigsSerializerRespond
	isSet bool
}

func (v NullableGrafanaConfigsSerializerRespond) Get() *GrafanaConfigsSerializerRespond {
	return v.value
}

func (v *NullableGrafanaConfigsSerializerRespond) Set(val *GrafanaConfigsSerializerRespond) {
	v.value = val
	v.isSet = true
}

func (v NullableGrafanaConfigsSerializerRespond) IsSet() bool {
	return v.isSet
}

func (v *NullableGrafanaConfigsSerializerRespond) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrafanaConfigsSerializerRespond(val *GrafanaConfigsSerializerRespond) *NullableGrafanaConfigsSerializerRespond {
	return &NullableGrafanaConfigsSerializerRespond{value: val, isSet: true}
}

func (v NullableGrafanaConfigsSerializerRespond) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrafanaConfigsSerializerRespond) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
