/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: 1.0
Contact: patrick.koss@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner struct for V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner
type V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner struct {
	// The source labels select values from existing labels. Their content is concatenated using the configured separator and matched against the configured regular expression for the replace, keep, and drop actions.
	SourceLabels []string `json:"sourceLabels,omitempty"`
	// Separator placed between concatenated source label values.
	Separator *string `json:"separator,omitempty"`
	// Label to which the resulting value is written in a replace action. It is mandatory for replace actions. Regex capture groups are available.
	TargetLabel *string `json:"targetLabel,omitempty"`
	// Regular expression against which the extracted value is matched.
	Regex *string `json:"regex,omitempty"`
	// Modulus to take of the hash of the source label values.
	Modulus *float32 `json:"modulus,omitempty"`
	// Replacement value against which a regex replace is performed if the regular expression matches. Regex capture groups are available.
	Replacement *string `json:"replacement,omitempty"`
	// Choice field ['replace', 'keep', 'drop', 'hashmod', 'labelmap', 'labeldrop', 'labelkeep']
	Action *string `json:"action,omitempty"`
}

// NewV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner instantiates a new V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner() *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner {
	this := V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner{}
	var separator string = ";"
	this.Separator = &separator
	var regex string = ".*"
	this.Regex = &regex
	var replacement string = "$1"
	this.Replacement = &replacement
	var action string = "replace"
	this.Action = &action
	return &this
}

// NewV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInnerWithDefaults instantiates a new V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInnerWithDefaults() *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner {
	this := V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner{}
	var separator string = ";"
	this.Separator = &separator
	var regex string = ".*"
	this.Regex = &regex
	var replacement string = "$1"
	this.Replacement = &replacement
	var action string = "replace"
	this.Action = &action
	return &this
}

// GetSourceLabels returns the SourceLabels field value if set, zero value otherwise.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetSourceLabels() []string {
	if o == nil || o.SourceLabels == nil {
		var ret []string
		return ret
	}
	return o.SourceLabels
}

// GetSourceLabelsOk returns a tuple with the SourceLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetSourceLabelsOk() ([]string, bool) {
	if o == nil || o.SourceLabels == nil {
		return nil, false
	}
	return o.SourceLabels, true
}

// HasSourceLabels returns a boolean if a field has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) HasSourceLabels() bool {
	if o != nil && o.SourceLabels != nil {
		return true
	}

	return false
}

// SetSourceLabels gets a reference to the given []string and assigns it to the SourceLabels field.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) SetSourceLabels(v []string) {
	o.SourceLabels = v
}

// GetSeparator returns the Separator field value if set, zero value otherwise.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetSeparator() string {
	if o == nil || o.Separator == nil {
		var ret string
		return ret
	}
	return *o.Separator
}

// GetSeparatorOk returns a tuple with the Separator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetSeparatorOk() (*string, bool) {
	if o == nil || o.Separator == nil {
		return nil, false
	}
	return o.Separator, true
}

// HasSeparator returns a boolean if a field has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) HasSeparator() bool {
	if o != nil && o.Separator != nil {
		return true
	}

	return false
}

// SetSeparator gets a reference to the given string and assigns it to the Separator field.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) SetSeparator(v string) {
	o.Separator = &v
}

// GetTargetLabel returns the TargetLabel field value if set, zero value otherwise.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetTargetLabel() string {
	if o == nil || o.TargetLabel == nil {
		var ret string
		return ret
	}
	return *o.TargetLabel
}

// GetTargetLabelOk returns a tuple with the TargetLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetTargetLabelOk() (*string, bool) {
	if o == nil || o.TargetLabel == nil {
		return nil, false
	}
	return o.TargetLabel, true
}

// HasTargetLabel returns a boolean if a field has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) HasTargetLabel() bool {
	if o != nil && o.TargetLabel != nil {
		return true
	}

	return false
}

// SetTargetLabel gets a reference to the given string and assigns it to the TargetLabel field.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) SetTargetLabel(v string) {
	o.TargetLabel = &v
}

// GetRegex returns the Regex field value if set, zero value otherwise.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetRegex() string {
	if o == nil || o.Regex == nil {
		var ret string
		return ret
	}
	return *o.Regex
}

// GetRegexOk returns a tuple with the Regex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetRegexOk() (*string, bool) {
	if o == nil || o.Regex == nil {
		return nil, false
	}
	return o.Regex, true
}

// HasRegex returns a boolean if a field has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) HasRegex() bool {
	if o != nil && o.Regex != nil {
		return true
	}

	return false
}

// SetRegex gets a reference to the given string and assigns it to the Regex field.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) SetRegex(v string) {
	o.Regex = &v
}

// GetModulus returns the Modulus field value if set, zero value otherwise.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetModulus() float32 {
	if o == nil || o.Modulus == nil {
		var ret float32
		return ret
	}
	return *o.Modulus
}

// GetModulusOk returns a tuple with the Modulus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetModulusOk() (*float32, bool) {
	if o == nil || o.Modulus == nil {
		return nil, false
	}
	return o.Modulus, true
}

// HasModulus returns a boolean if a field has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) HasModulus() bool {
	if o != nil && o.Modulus != nil {
		return true
	}

	return false
}

// SetModulus gets a reference to the given float32 and assigns it to the Modulus field.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) SetModulus(v float32) {
	o.Modulus = &v
}

// GetReplacement returns the Replacement field value if set, zero value otherwise.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetReplacement() string {
	if o == nil || o.Replacement == nil {
		var ret string
		return ret
	}
	return *o.Replacement
}

// GetReplacementOk returns a tuple with the Replacement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetReplacementOk() (*string, bool) {
	if o == nil || o.Replacement == nil {
		return nil, false
	}
	return o.Replacement, true
}

// HasReplacement returns a boolean if a field has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) HasReplacement() bool {
	if o != nil && o.Replacement != nil {
		return true
	}

	return false
}

// SetReplacement gets a reference to the given string and assigns it to the Replacement field.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) SetReplacement(v string) {
	o.Replacement = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetAction() string {
	if o == nil || o.Action == nil {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) GetActionOk() (*string, bool) {
	if o == nil || o.Action == nil {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) HasAction() bool {
	if o != nil && o.Action != nil {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) SetAction(v string) {
	o.Action = &v
}

func (o V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SourceLabels != nil {
		toSerialize["sourceLabels"] = o.SourceLabels
	}
	if o.Separator != nil {
		toSerialize["separator"] = o.Separator
	}
	if o.TargetLabel != nil {
		toSerialize["targetLabel"] = o.TargetLabel
	}
	if o.Regex != nil {
		toSerialize["regex"] = o.Regex
	}
	if o.Modulus != nil {
		toSerialize["modulus"] = o.Modulus
	}
	if o.Replacement != nil {
		toSerialize["replacement"] = o.Replacement
	}
	if o.Action != nil {
		toSerialize["action"] = o.Action
	}
	return json.Marshal(toSerialize)
}

type NullableV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner struct {
	value *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner
	isSet bool
}

func (v NullableV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) Get() *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner {
	return v.value
}

func (v *NullableV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) Set(val *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner(val *V1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) *NullableV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner {
	return &NullableV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner{value: val, isSet: true}
}

func (v NullableV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1InstancesScrapeconfigsCreateRequestMetricsRelabelConfigsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
