/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: v1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// V1InstancesAlertconfigsUpdateRequestRoute The root node of the routing tree.
type V1InstancesAlertconfigsUpdateRequestRoute struct {
	// Receiver that should be one item of receivers `Additional Validators:` * must be a in name of receivers
	Receiver string `json:"receiver"`
	// The labels by which incoming alerts are grouped together. For example, multiple alerts coming in for cluster=A and alertname=LatencyHigh would be batched into a single group. To aggregate by all possible labels use the special value '...' as the sole label name, for example: group_by: ['...']. This effectively disables aggregation entirely, passing through all alerts as-is. This is unlikely to be what you want, unless you have a very low alert volume or your upstream notification system performs its own grouping.
	GroupBy []string `json:"groupBy,omitempty"`
	// How long to initially wait to send a notification for a group of alerts. Allows to wait for an inhibiting alert to arrive or collect more initial alerts for the same group. (Usually ~0s to few minutes.) `Additional Validators:` * must be a valid time format
	GroupWait *string `json:"groupWait,omitempty"`
	// How long to wait before sending a notification about new alerts that are added to a group of alerts for which an initial notification has already been sent. (Usually ~5m or more.) `Additional Validators:` * must be a valid time format
	GroupInterval *string `json:"groupInterval,omitempty"`
	// How long to wait before sending a notification again if it has already been sent successfully for an alert. (Usually ~3h or more). `Additional Validators:` * must be a valid time format
	RepeatInterval *string `json:"repeatInterval,omitempty"`
	// map of key:value. A set of equality matchers an alert has to fulfill to match the node.  `Additional Validators:` * should not contain more than 5 keys * each key and value should not be longer than 200 characters * key and values should only include the characters: a-zA-Z0-9_./@&?:-
	Match map[string]interface{} `json:"match,omitempty"`
	// map of key:value. A set of regex-matchers an alert has to fulfill to match the node.  `Additional Validators:` * should not contain more than 5 keys * each key and value should not be longer than 200 characters
	MatchRe map[string]interface{} `json:"matchRe,omitempty"`
	// A list of matchers that an alert has to fulfill to match the node. A matcher is a string with a syntax inspired by PromQL and OpenMetrics. The syntax of a matcher consists of three tokens: * A valid Prometheus label name. * One of =, !=, =~, or !~. = means equals, != means that the strings are not equal, =~ is used for equality of regex expressions and !~ is used for un-equality of regex expressions. They have the same meaning as known from PromQL selectors. * A UTF-8 string, which may be enclosed in double quotes. Before or after each token, there may be any amount of whitespace. `Additional Validators:` * should not contain more than 5 keys * each key and value should not be longer than 200 characters
	Matchers []string `json:"matchers,omitempty"`
	// Zero or more child routes.
	Routes []V1InstancesAlertconfigsUpdateRequestRouteRoutesInner `json:"routes,omitempty"`
}

// NewV1InstancesAlertconfigsUpdateRequestRoute instantiates a new V1InstancesAlertconfigsUpdateRequestRoute object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1InstancesAlertconfigsUpdateRequestRoute(receiver string) *V1InstancesAlertconfigsUpdateRequestRoute {
	this := V1InstancesAlertconfigsUpdateRequestRoute{}
	this.Receiver = receiver
	var groupWait string = "30s"
	this.GroupWait = &groupWait
	var groupInterval string = "5m"
	this.GroupInterval = &groupInterval
	var repeatInterval string = "4h"
	this.RepeatInterval = &repeatInterval
	return &this
}

// NewV1InstancesAlertconfigsUpdateRequestRouteWithDefaults instantiates a new V1InstancesAlertconfigsUpdateRequestRoute object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1InstancesAlertconfigsUpdateRequestRouteWithDefaults() *V1InstancesAlertconfigsUpdateRequestRoute {
	this := V1InstancesAlertconfigsUpdateRequestRoute{}
	var groupWait string = "30s"
	this.GroupWait = &groupWait
	var groupInterval string = "5m"
	this.GroupInterval = &groupInterval
	var repeatInterval string = "4h"
	this.RepeatInterval = &repeatInterval
	return &this
}

// GetReceiver returns the Receiver field value
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetReceiver() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Receiver
}

// GetReceiverOk returns a tuple with the Receiver field value
// and a boolean to check if the value has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetReceiverOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Receiver, true
}

// SetReceiver sets field value
func (o *V1InstancesAlertconfigsUpdateRequestRoute) SetReceiver(v string) {
	o.Receiver = v
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetGroupBy() []string {
	if o == nil || o.GroupBy == nil {
		var ret []string
		return ret
	}
	return o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetGroupByOk() ([]string, bool) {
	if o == nil || o.GroupBy == nil {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) HasGroupBy() bool {
	if o != nil && o.GroupBy != nil {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given []string and assigns it to the GroupBy field.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) SetGroupBy(v []string) {
	o.GroupBy = v
}

// GetGroupWait returns the GroupWait field value if set, zero value otherwise.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetGroupWait() string {
	if o == nil || o.GroupWait == nil {
		var ret string
		return ret
	}
	return *o.GroupWait
}

// GetGroupWaitOk returns a tuple with the GroupWait field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetGroupWaitOk() (*string, bool) {
	if o == nil || o.GroupWait == nil {
		return nil, false
	}
	return o.GroupWait, true
}

// HasGroupWait returns a boolean if a field has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) HasGroupWait() bool {
	if o != nil && o.GroupWait != nil {
		return true
	}

	return false
}

// SetGroupWait gets a reference to the given string and assigns it to the GroupWait field.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) SetGroupWait(v string) {
	o.GroupWait = &v
}

// GetGroupInterval returns the GroupInterval field value if set, zero value otherwise.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetGroupInterval() string {
	if o == nil || o.GroupInterval == nil {
		var ret string
		return ret
	}
	return *o.GroupInterval
}

// GetGroupIntervalOk returns a tuple with the GroupInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetGroupIntervalOk() (*string, bool) {
	if o == nil || o.GroupInterval == nil {
		return nil, false
	}
	return o.GroupInterval, true
}

// HasGroupInterval returns a boolean if a field has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) HasGroupInterval() bool {
	if o != nil && o.GroupInterval != nil {
		return true
	}

	return false
}

// SetGroupInterval gets a reference to the given string and assigns it to the GroupInterval field.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) SetGroupInterval(v string) {
	o.GroupInterval = &v
}

// GetRepeatInterval returns the RepeatInterval field value if set, zero value otherwise.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetRepeatInterval() string {
	if o == nil || o.RepeatInterval == nil {
		var ret string
		return ret
	}
	return *o.RepeatInterval
}

// GetRepeatIntervalOk returns a tuple with the RepeatInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetRepeatIntervalOk() (*string, bool) {
	if o == nil || o.RepeatInterval == nil {
		return nil, false
	}
	return o.RepeatInterval, true
}

// HasRepeatInterval returns a boolean if a field has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) HasRepeatInterval() bool {
	if o != nil && o.RepeatInterval != nil {
		return true
	}

	return false
}

// SetRepeatInterval gets a reference to the given string and assigns it to the RepeatInterval field.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) SetRepeatInterval(v string) {
	o.RepeatInterval = &v
}

// GetMatch returns the Match field value if set, zero value otherwise.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetMatch() map[string]interface{} {
	if o == nil || o.Match == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Match
}

// GetMatchOk returns a tuple with the Match field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetMatchOk() (map[string]interface{}, bool) {
	if o == nil || o.Match == nil {
		return nil, false
	}
	return o.Match, true
}

// HasMatch returns a boolean if a field has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) HasMatch() bool {
	if o != nil && o.Match != nil {
		return true
	}

	return false
}

// SetMatch gets a reference to the given map[string]interface{} and assigns it to the Match field.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) SetMatch(v map[string]interface{}) {
	o.Match = v
}

// GetMatchRe returns the MatchRe field value if set, zero value otherwise.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetMatchRe() map[string]interface{} {
	if o == nil || o.MatchRe == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.MatchRe
}

// GetMatchReOk returns a tuple with the MatchRe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetMatchReOk() (map[string]interface{}, bool) {
	if o == nil || o.MatchRe == nil {
		return nil, false
	}
	return o.MatchRe, true
}

// HasMatchRe returns a boolean if a field has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) HasMatchRe() bool {
	if o != nil && o.MatchRe != nil {
		return true
	}

	return false
}

// SetMatchRe gets a reference to the given map[string]interface{} and assigns it to the MatchRe field.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) SetMatchRe(v map[string]interface{}) {
	o.MatchRe = v
}

// GetMatchers returns the Matchers field value if set, zero value otherwise.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetMatchers() []string {
	if o == nil || o.Matchers == nil {
		var ret []string
		return ret
	}
	return o.Matchers
}

// GetMatchersOk returns a tuple with the Matchers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetMatchersOk() ([]string, bool) {
	if o == nil || o.Matchers == nil {
		return nil, false
	}
	return o.Matchers, true
}

// HasMatchers returns a boolean if a field has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) HasMatchers() bool {
	if o != nil && o.Matchers != nil {
		return true
	}

	return false
}

// SetMatchers gets a reference to the given []string and assigns it to the Matchers field.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) SetMatchers(v []string) {
	o.Matchers = v
}

// GetRoutes returns the Routes field value if set, zero value otherwise.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetRoutes() []V1InstancesAlertconfigsUpdateRequestRouteRoutesInner {
	if o == nil || o.Routes == nil {
		var ret []V1InstancesAlertconfigsUpdateRequestRouteRoutesInner
		return ret
	}
	return o.Routes
}

// GetRoutesOk returns a tuple with the Routes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) GetRoutesOk() ([]V1InstancesAlertconfigsUpdateRequestRouteRoutesInner, bool) {
	if o == nil || o.Routes == nil {
		return nil, false
	}
	return o.Routes, true
}

// HasRoutes returns a boolean if a field has been set.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) HasRoutes() bool {
	if o != nil && o.Routes != nil {
		return true
	}

	return false
}

// SetRoutes gets a reference to the given []V1InstancesAlertconfigsUpdateRequestRouteRoutesInner and assigns it to the Routes field.
func (o *V1InstancesAlertconfigsUpdateRequestRoute) SetRoutes(v []V1InstancesAlertconfigsUpdateRequestRouteRoutesInner) {
	o.Routes = v
}

func (o V1InstancesAlertconfigsUpdateRequestRoute) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["receiver"] = o.Receiver
	}
	if o.GroupBy != nil {
		toSerialize["groupBy"] = o.GroupBy
	}
	if o.GroupWait != nil {
		toSerialize["groupWait"] = o.GroupWait
	}
	if o.GroupInterval != nil {
		toSerialize["groupInterval"] = o.GroupInterval
	}
	if o.RepeatInterval != nil {
		toSerialize["repeatInterval"] = o.RepeatInterval
	}
	if o.Match != nil {
		toSerialize["match"] = o.Match
	}
	if o.MatchRe != nil {
		toSerialize["matchRe"] = o.MatchRe
	}
	if o.Matchers != nil {
		toSerialize["matchers"] = o.Matchers
	}
	if o.Routes != nil {
		toSerialize["routes"] = o.Routes
	}
	return json.Marshal(toSerialize)
}

type NullableV1InstancesAlertconfigsUpdateRequestRoute struct {
	value *V1InstancesAlertconfigsUpdateRequestRoute
	isSet bool
}

func (v NullableV1InstancesAlertconfigsUpdateRequestRoute) Get() *V1InstancesAlertconfigsUpdateRequestRoute {
	return v.value
}

func (v *NullableV1InstancesAlertconfigsUpdateRequestRoute) Set(val *V1InstancesAlertconfigsUpdateRequestRoute) {
	v.value = val
	v.isSet = true
}

func (v NullableV1InstancesAlertconfigsUpdateRequestRoute) IsSet() bool {
	return v.isSet
}

func (v *NullableV1InstancesAlertconfigsUpdateRequestRoute) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1InstancesAlertconfigsUpdateRequestRoute(val *V1InstancesAlertconfigsUpdateRequestRoute) *NullableV1InstancesAlertconfigsUpdateRequestRoute {
	return &NullableV1InstancesAlertconfigsUpdateRequestRoute{value: val, isSet: true}
}

func (v NullableV1InstancesAlertconfigsUpdateRequestRoute) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1InstancesAlertconfigsUpdateRequestRoute) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


