/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: v1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// PlanModel struct for PlanModel
type PlanModel struct {
	PlanId string `json:"planId"`
	Description *string `json:"description,omitempty"`
	BucketSize int32 `json:"bucketSize"`
	GrafanaGlobalUsers int32 `json:"grafanaGlobalUsers"`
	GrafanaGlobalOrgs int32 `json:"grafanaGlobalOrgs"`
	GrafanaGlobalDashboards int32 `json:"grafanaGlobalDashboards"`
	AlertRules int32 `json:"alertRules"`
	TargetNumber int32 `json:"targetNumber"`
	SamplesPerScrape int32 `json:"samplesPerScrape"`
	GrafanaGlobalSessions int32 `json:"grafanaGlobalSessions"`
	Name *string `json:"name,omitempty"`
	Amount *float32 `json:"amount,omitempty"`
	AlertReceivers int32 `json:"alertReceivers"`
	AlertMatchers int32 `json:"alertMatchers"`
	LogsStorage int32 `json:"logsStorage"`
	TracesStorage int32 `json:"tracesStorage"`
	LogsAlert int32 `json:"logsAlert"`
}

// NewPlanModel instantiates a new PlanModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanModel(planId string, bucketSize int32, grafanaGlobalUsers int32, grafanaGlobalOrgs int32, grafanaGlobalDashboards int32, alertRules int32, targetNumber int32, samplesPerScrape int32, grafanaGlobalSessions int32, alertReceivers int32, alertMatchers int32, logsStorage int32, tracesStorage int32, logsAlert int32) *PlanModel {
	this := PlanModel{}
	this.PlanId = planId
	this.BucketSize = bucketSize
	this.GrafanaGlobalUsers = grafanaGlobalUsers
	this.GrafanaGlobalOrgs = grafanaGlobalOrgs
	this.GrafanaGlobalDashboards = grafanaGlobalDashboards
	this.AlertRules = alertRules
	this.TargetNumber = targetNumber
	this.SamplesPerScrape = samplesPerScrape
	this.GrafanaGlobalSessions = grafanaGlobalSessions
	var name string = ""
	this.Name = &name
	this.AlertReceivers = alertReceivers
	this.AlertMatchers = alertMatchers
	this.LogsStorage = logsStorage
	this.TracesStorage = tracesStorage
	this.LogsAlert = logsAlert
	return &this
}

// NewPlanModelWithDefaults instantiates a new PlanModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanModelWithDefaults() *PlanModel {
	this := PlanModel{}
	var name string = ""
	this.Name = &name
	return &this
}

// GetPlanId returns the PlanId field value
func (o *PlanModel) GetPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetPlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *PlanModel) SetPlanId(v string) {
	o.PlanId = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PlanModel) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanModel) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PlanModel) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PlanModel) SetDescription(v string) {
	o.Description = &v
}

// GetBucketSize returns the BucketSize field value
func (o *PlanModel) GetBucketSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BucketSize
}

// GetBucketSizeOk returns a tuple with the BucketSize field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetBucketSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BucketSize, true
}

// SetBucketSize sets field value
func (o *PlanModel) SetBucketSize(v int32) {
	o.BucketSize = v
}

// GetGrafanaGlobalUsers returns the GrafanaGlobalUsers field value
func (o *PlanModel) GetGrafanaGlobalUsers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GrafanaGlobalUsers
}

// GetGrafanaGlobalUsersOk returns a tuple with the GrafanaGlobalUsers field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetGrafanaGlobalUsersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrafanaGlobalUsers, true
}

// SetGrafanaGlobalUsers sets field value
func (o *PlanModel) SetGrafanaGlobalUsers(v int32) {
	o.GrafanaGlobalUsers = v
}

// GetGrafanaGlobalOrgs returns the GrafanaGlobalOrgs field value
func (o *PlanModel) GetGrafanaGlobalOrgs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GrafanaGlobalOrgs
}

// GetGrafanaGlobalOrgsOk returns a tuple with the GrafanaGlobalOrgs field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetGrafanaGlobalOrgsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrafanaGlobalOrgs, true
}

// SetGrafanaGlobalOrgs sets field value
func (o *PlanModel) SetGrafanaGlobalOrgs(v int32) {
	o.GrafanaGlobalOrgs = v
}

// GetGrafanaGlobalDashboards returns the GrafanaGlobalDashboards field value
func (o *PlanModel) GetGrafanaGlobalDashboards() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GrafanaGlobalDashboards
}

// GetGrafanaGlobalDashboardsOk returns a tuple with the GrafanaGlobalDashboards field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetGrafanaGlobalDashboardsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrafanaGlobalDashboards, true
}

// SetGrafanaGlobalDashboards sets field value
func (o *PlanModel) SetGrafanaGlobalDashboards(v int32) {
	o.GrafanaGlobalDashboards = v
}

// GetAlertRules returns the AlertRules field value
func (o *PlanModel) GetAlertRules() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AlertRules
}

// GetAlertRulesOk returns a tuple with the AlertRules field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetAlertRulesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlertRules, true
}

// SetAlertRules sets field value
func (o *PlanModel) SetAlertRules(v int32) {
	o.AlertRules = v
}

// GetTargetNumber returns the TargetNumber field value
func (o *PlanModel) GetTargetNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TargetNumber
}

// GetTargetNumberOk returns a tuple with the TargetNumber field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetTargetNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetNumber, true
}

// SetTargetNumber sets field value
func (o *PlanModel) SetTargetNumber(v int32) {
	o.TargetNumber = v
}

// GetSamplesPerScrape returns the SamplesPerScrape field value
func (o *PlanModel) GetSamplesPerScrape() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SamplesPerScrape
}

// GetSamplesPerScrapeOk returns a tuple with the SamplesPerScrape field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetSamplesPerScrapeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SamplesPerScrape, true
}

// SetSamplesPerScrape sets field value
func (o *PlanModel) SetSamplesPerScrape(v int32) {
	o.SamplesPerScrape = v
}

// GetGrafanaGlobalSessions returns the GrafanaGlobalSessions field value
func (o *PlanModel) GetGrafanaGlobalSessions() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GrafanaGlobalSessions
}

// GetGrafanaGlobalSessionsOk returns a tuple with the GrafanaGlobalSessions field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetGrafanaGlobalSessionsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrafanaGlobalSessions, true
}

// SetGrafanaGlobalSessions sets field value
func (o *PlanModel) SetGrafanaGlobalSessions(v int32) {
	o.GrafanaGlobalSessions = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PlanModel) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanModel) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PlanModel) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PlanModel) SetName(v string) {
	o.Name = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *PlanModel) GetAmount() float32 {
	if o == nil || o.Amount == nil {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanModel) GetAmountOk() (*float32, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *PlanModel) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *PlanModel) SetAmount(v float32) {
	o.Amount = &v
}

// GetAlertReceivers returns the AlertReceivers field value
func (o *PlanModel) GetAlertReceivers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AlertReceivers
}

// GetAlertReceiversOk returns a tuple with the AlertReceivers field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetAlertReceiversOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlertReceivers, true
}

// SetAlertReceivers sets field value
func (o *PlanModel) SetAlertReceivers(v int32) {
	o.AlertReceivers = v
}

// GetAlertMatchers returns the AlertMatchers field value
func (o *PlanModel) GetAlertMatchers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AlertMatchers
}

// GetAlertMatchersOk returns a tuple with the AlertMatchers field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetAlertMatchersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AlertMatchers, true
}

// SetAlertMatchers sets field value
func (o *PlanModel) SetAlertMatchers(v int32) {
	o.AlertMatchers = v
}

// GetLogsStorage returns the LogsStorage field value
func (o *PlanModel) GetLogsStorage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LogsStorage
}

// GetLogsStorageOk returns a tuple with the LogsStorage field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetLogsStorageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogsStorage, true
}

// SetLogsStorage sets field value
func (o *PlanModel) SetLogsStorage(v int32) {
	o.LogsStorage = v
}

// GetTracesStorage returns the TracesStorage field value
func (o *PlanModel) GetTracesStorage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TracesStorage
}

// GetTracesStorageOk returns a tuple with the TracesStorage field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetTracesStorageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TracesStorage, true
}

// SetTracesStorage sets field value
func (o *PlanModel) SetTracesStorage(v int32) {
	o.TracesStorage = v
}

// GetLogsAlert returns the LogsAlert field value
func (o *PlanModel) GetLogsAlert() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LogsAlert
}

// GetLogsAlertOk returns a tuple with the LogsAlert field value
// and a boolean to check if the value has been set.
func (o *PlanModel) GetLogsAlertOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogsAlert, true
}

// SetLogsAlert sets field value
func (o *PlanModel) SetLogsAlert(v int32) {
	o.LogsAlert = v
}

func (o PlanModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["planId"] = o.PlanId
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["bucketSize"] = o.BucketSize
	}
	if true {
		toSerialize["grafanaGlobalUsers"] = o.GrafanaGlobalUsers
	}
	if true {
		toSerialize["grafanaGlobalOrgs"] = o.GrafanaGlobalOrgs
	}
	if true {
		toSerialize["grafanaGlobalDashboards"] = o.GrafanaGlobalDashboards
	}
	if true {
		toSerialize["alertRules"] = o.AlertRules
	}
	if true {
		toSerialize["targetNumber"] = o.TargetNumber
	}
	if true {
		toSerialize["samplesPerScrape"] = o.SamplesPerScrape
	}
	if true {
		toSerialize["grafanaGlobalSessions"] = o.GrafanaGlobalSessions
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["alertReceivers"] = o.AlertReceivers
	}
	if true {
		toSerialize["alertMatchers"] = o.AlertMatchers
	}
	if true {
		toSerialize["logsStorage"] = o.LogsStorage
	}
	if true {
		toSerialize["tracesStorage"] = o.TracesStorage
	}
	if true {
		toSerialize["logsAlert"] = o.LogsAlert
	}
	return json.Marshal(toSerialize)
}

type NullablePlanModel struct {
	value *PlanModel
	isSet bool
}

func (v NullablePlanModel) Get() *PlanModel {
	return v.value
}

func (v *NullablePlanModel) Set(val *PlanModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanModel(val *PlanModel) *NullablePlanModel {
	return &NullablePlanModel{value: val, isSet: true}
}

func (v NullablePlanModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


