/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: v1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// LogsConfigResponse struct for LogsConfigResponse
type LogsConfigResponse struct {
	Message string `json:"message"`
	Config LogsConfig `json:"config"`
}

// NewLogsConfigResponse instantiates a new LogsConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogsConfigResponse(message string, config LogsConfig) *LogsConfigResponse {
	this := LogsConfigResponse{}
	this.Message = message
	this.Config = config
	return &this
}

// NewLogsConfigResponseWithDefaults instantiates a new LogsConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogsConfigResponseWithDefaults() *LogsConfigResponse {
	this := LogsConfigResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *LogsConfigResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *LogsConfigResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *LogsConfigResponse) SetMessage(v string) {
	o.Message = v
}

// GetConfig returns the Config field value
func (o *LogsConfigResponse) GetConfig() LogsConfig {
	if o == nil {
		var ret LogsConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *LogsConfigResponse) GetConfigOk() (*LogsConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *LogsConfigResponse) SetConfig(v LogsConfig) {
	o.Config = v
}

func (o LogsConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["message"] = o.Message
	}
	if true {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableLogsConfigResponse struct {
	value *LogsConfigResponse
	isSet bool
}

func (v NullableLogsConfigResponse) Get() *LogsConfigResponse {
	return v.value
}

func (v *NullableLogsConfigResponse) Set(val *LogsConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLogsConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLogsConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogsConfigResponse(val *LogsConfigResponse) *NullableLogsConfigResponse {
	return &NullableLogsConfigResponse{value: val, isSet: true}
}

func (v NullableLogsConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogsConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


