/*
STACKIT Argus API

API endpoints for Argus on STACKIT

API version: v1
Contact: stackit-argus@mail.schwarz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package argus

import (
	"encoding/json"
)

// GrafanaPluginModel struct for GrafanaPluginModel
type GrafanaPluginModel struct {
	Name string `json:"name"`
	Description string `json:"description"`
}

// NewGrafanaPluginModel instantiates a new GrafanaPluginModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrafanaPluginModel(name string, description string) *GrafanaPluginModel {
	this := GrafanaPluginModel{}
	this.Name = name
	this.Description = description
	return &this
}

// NewGrafanaPluginModelWithDefaults instantiates a new GrafanaPluginModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrafanaPluginModelWithDefaults() *GrafanaPluginModel {
	this := GrafanaPluginModel{}
	return &this
}

// GetName returns the Name field value
func (o *GrafanaPluginModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GrafanaPluginModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GrafanaPluginModel) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *GrafanaPluginModel) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *GrafanaPluginModel) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *GrafanaPluginModel) SetDescription(v string) {
	o.Description = v
}

func (o GrafanaPluginModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableGrafanaPluginModel struct {
	value *GrafanaPluginModel
	isSet bool
}

func (v NullableGrafanaPluginModel) Get() *GrafanaPluginModel {
	return v.value
}

func (v *NullableGrafanaPluginModel) Set(val *GrafanaPluginModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGrafanaPluginModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGrafanaPluginModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrafanaPluginModel(val *GrafanaPluginModel) *NullableGrafanaPluginModel {
	return &NullableGrafanaPluginModel{value: val, isSet: true}
}

func (v NullableGrafanaPluginModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrafanaPluginModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


